const OK = 200;
const CREATED = 201;
const PROCESS_EXIT = 1;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;

module.exports = { OK, CREATED, BAD_REQUEST, UNAUTHORIZED, NOT_FOUND, PROCESS_EXIT };
